// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhLUZxc-s2xXZHwojBgd5thFa2xw3POo',
    appId: '1:1025716753868:web:2ebf5636486677c3b43969',
    messagingSenderId: '1025716753868',
    projectId: 'boggle-663ae',
    authDomain: 'boggle-663ae.firebaseapp.com',
    storageBucket: 'boggle-663ae.appspot.com',
    measurementId: 'G-50VJ7S565F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeC0aFMwKraS9ic8WC3dke-VBG91D0KNs',
    appId: '1:1025716753868:android:ef588c430e0a39d1b43969',
    messagingSenderId: '1025716753868',
    projectId: 'boggle-663ae',
    storageBucket: 'boggle-663ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb9z3lwU-Y0y4fwLwJlDx-Liiab8I7bR0',
    appId: '1:1025716753868:ios:c3ddad4c9c84df14b43969',
    messagingSenderId: '1025716753868',
    projectId: 'boggle-663ae',
    storageBucket: 'boggle-663ae.appspot.com',
    iosClientId: '1025716753868-ifnvtjt9tud541v6lu34p81sjtki7d66.apps.googleusercontent.com',
    iosBundleId: 'com.maxshaberman.boggle',
  );
}
